package vista;

import aplicacion.FachadaAplicacion;
import aplicacion.Regulador;
import javax.swing.JFrame;
import vista.componentes.ColoresGUI;
import vista.componentes.DialogoInfo;
import vista.componentes.FuentesGUI;
import vista.componentes.ImagenesGUI;

/**
 * Ventana emergente (DIALOG) para ver y/o modificar la comisión en las 
 * operaciones de compra/venta fijada por el regulador
 */

public class AjustarComision extends javax.swing.JDialog {

    // Solo cogemos la antigua al abrir la ventana y ponemos la nueva al 
    // cerrarla por el botón de confirmar, no hay actualizaciones dinámicas
    private float antiguaComision, nuevaComision = -1.0f;
    private Regulador regulador;

    public AjustarComision(JFrame owner, Regulador regulador) {
        super(owner, true);
        this.regulador = regulador;
        initComponents();
        this.setVisible(true);
        this.setTitle("Modificación de comisión");
        this.setIconImage(ImagenesGUI.getImage("database.png", 32));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new vista.componentes.Etiqueta();
        comisionActual = new vista.componentes.Etiqueta();
        fijarComisionLabel = new vista.componentes.Etiqueta();
        botonAplicar = new vista.componentes.Boton();
        botonCerrar = new vista.componentes.Boton();
        nuevaComisionTextBox = new vista.componentes.TextBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titulo.setText("Fijar comisión");

        comisionActual.setText("Comisión actual: " + String.format("%.2f", FachadaAplicacion.getInstance().obtenerComision(regulador)).replace(',', '.') + "%"
        );

        fijarComisionLabel.setText("Fijar nueva comisión: ");

        botonAplicar.setText("Aplicar");
        botonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAplicarActionPerformed(evt);
            }
        });

        botonCerrar.setText("Cerrar");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        nuevaComisionTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaComisionTextBoxActionPerformed(evt);
            }
        });
        nuevaComisionTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nuevaComisionTextBoxKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comisionActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(212, 212, 212))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(fijarComisionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nuevaComisionTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(comisionActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fijarComisionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevaComisionTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        titulo.setFont(FuentesGUI.getFuente(FuentesGUI.Modificador.NORMAL,
            FuentesGUI.Size.GRANDE));
    nuevaComisionTextBox.setText(String.format("%.2f", this.antiguaComision).replace(',', '.'));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAplicarActionPerformed
        float temp = -1.0f;
        try {
            temp = Float.parseFloat(nuevaComisionTextBox.getText());
            if (temp >= 0.0f && temp < 1.0f) {
                nuevaComision = temp;
                nuevaComisionTextBox.setBackground(ColoresGUI.blanco);
            } else {
                nuevaComisionTextBox.setBackground(ColoresGUI.getGUIColorExtraClaro(ColoresGUI.Colores.ROJO));
                nuevaComision = -1.0f;
            }
        } catch (NumberFormatException e) {
            nuevaComisionTextBox.setBackground(ColoresGUI.getGUIColorExtraClaro(ColoresGUI.Colores.ROJO));
            nuevaComision = -1.0f;
        }
        if (nuevaComision >= 0.0f && nuevaComision < 1.0f) {
            FachadaAplicacion.getInstance().modificarComision(regulador, nuevaComision);
            FachadaAplicacion.getInstance().muestraExcepcion("Se ha configurado la comisión a " + 
                    String.format("%.2f", nuevaComision).replace(',', '.') + "% con éxito!", DialogoInfo.NivelDeAdvertencia.INFORMACION);
            nuevaComisionTextBox.setBackground(ColoresGUI.blanco);
            this.dispose();
        } else {
            nuevaComisionTextBox.setBackground(ColoresGUI.getGUIColorExtraClaro(ColoresGUI.Colores.ROJO));
            nuevaComision = -1.0f;
            FachadaAplicacion.getInstance().muestraExcepcion("La nueva comisión introducida no es válida", DialogoInfo.NivelDeAdvertencia.ADVERTENCIA);
        }
    }//GEN-LAST:event_botonAplicarActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void nuevaComisionTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaComisionTextBoxActionPerformed
         // Validar entrada correcta
        float temp = -1.0f;
        try {
            temp = Float.parseFloat(nuevaComisionTextBox.getText());
            if (temp >= 0.0f && temp < 1.0f) {
                nuevaComision = temp;
                nuevaComisionTextBox.setBackground(ColoresGUI.blanco);
            } else {
                nuevaComisionTextBox.setBackground(ColoresGUI.getGUIColorExtraClaro(ColoresGUI.Colores.ROJO));
                nuevaComision = -1.0f;
            }
        } catch (NumberFormatException e) {
            nuevaComisionTextBox.setBackground(ColoresGUI.getGUIColorExtraClaro(ColoresGUI.Colores.ROJO));
            nuevaComision = -1.0f;
        }
    }//GEN-LAST:event_nuevaComisionTextBoxActionPerformed

    private void nuevaComisionTextBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuevaComisionTextBoxKeyTyped
        // Validar entrada correcta
        float temp = -1.0f;
        try {
            temp = Float.parseFloat(nuevaComisionTextBox.getText());
            if (temp >= 0.0f && temp < 1.0f) {
                nuevaComision = temp;
                nuevaComisionTextBox.setBackground(ColoresGUI.blanco);
            } else {
                nuevaComisionTextBox.setBackground(ColoresGUI.getGUIColorExtraClaro(ColoresGUI.Colores.ROJO));
                nuevaComision = -1.0f;
            }
        } catch (NumberFormatException e) {
            nuevaComisionTextBox.setBackground(ColoresGUI.getGUIColorExtraClaro(ColoresGUI.Colores.ROJO));
            nuevaComision = -1.0f;
        }
    }//GEN-LAST:event_nuevaComisionTextBoxKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.componentes.Boton botonAplicar;
    private vista.componentes.Boton botonCerrar;
    private vista.componentes.Etiqueta comisionActual;
    private vista.componentes.Etiqueta fijarComisionLabel;
    private vista.componentes.TextBox nuevaComisionTextBox;
    private vista.componentes.Etiqueta titulo;
    // End of variables declaration//GEN-END:variables
}