package vista;

import aplicacion.EntradaParticipacion;
import aplicacion.FachadaAplicacion;
import aplicacion.Usuario;
import java.awt.Point;
import java.awt.event.MouseEvent;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.JTableHeader;

import vista.componentes.FuentesGUI;
import vista.modeloTablas.ModeloTablaHistorial;

import vista.modeloTablas.ModeloTablaParticipaciones;

public class VerParticipacionesPanel extends javax.swing.JPanel {

    /**
     * Panel donde se consultan las participaciones disponibles en cada empresa
     */
    private Usuario u;
    private FachadaAplicacion fa;
    private List<EntradaParticipacion> listaActual;

    public VerParticipacionesPanel() {
        // No usar, requerido por NetBeans
        initComponents();
    }

    public VerParticipacionesPanel(Usuario usuario, FachadaAplicacion fa) {
        this.u = usuario;
        this.fa = fa;
        initComponents();
        actualizarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new vista.componentes.Etiqueta();
        filtroEmpesaLabel = new vista.componentes.Etiqueta();
        filtroEmpresa = new vista.componentes.TextBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaParticipaciones = new vista.componentes.Tabla();
        totalParticipacionesLabel = new vista.componentes.Etiqueta();
        totalParticipaciones = new vista.componentes.Etiqueta();
        empresasDiferentesLabel = new vista.componentes.Etiqueta();
        empresasDiferentes = new vista.componentes.Etiqueta();

        setPreferredSize(new java.awt.Dimension(900, 600));

        titulo.setText("Lista de participaciones");
        titulo.setName("titulo"); // NOI18N

        filtroEmpesaLabel.setText("Empresa:");
        filtroEmpesaLabel.setName("filtroEmpesaLabel"); // NOI18N

        filtroEmpresa.setName("filtroEmpresa"); // NOI18N
        filtroEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroEmpresaActionPerformed(evt);
            }
        });
        filtroEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filtroEmpresaKeyTyped(evt);
            }

            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtroEmpresaKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtroEmpresaKeyReleased(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablaParticipaciones.setModel(new ModeloTablaParticipaciones()
        );
        tablaParticipaciones.setName("tablaParticipaciones"); // NOI18N
        jScrollPane1.setViewportView(tablaParticipaciones);

        totalParticipacionesLabel.setText("Total de participaciones:");
        totalParticipacionesLabel.setName("totalParticipacionesLabel"); // NOI18N

        totalParticipaciones.setText("0");
        totalParticipaciones.setName("totalParticipaciones"); // NOI18N

        empresasDiferentesLabel.setText("Empresas diferentes:");
        empresasDiferentesLabel.setName("empresasDiferentesLabel"); // NOI18N

        empresasDiferentes.setText("0");
        empresasDiferentes.setName("empresasDiferentes"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(filtroEmpesaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(filtroEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(totalParticipacionesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(totalParticipaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(empresasDiferentesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(empresasDiferentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(filtroEmpesaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(filtroEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(totalParticipacionesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(totalParticipaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(empresasDiferentesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(empresasDiferentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(103, Short.MAX_VALUE))
        );

        titulo.setFont(FuentesGUI.getFuente(FuentesGUI.Modificador.NORMAL,
                FuentesGUI.Size.GRANDE));
        totalParticipaciones.setFont(FuentesGUI.getFuente(FuentesGUI.Modificador.NEGRITA,
                FuentesGUI.Size.GRANDE));
        empresasDiferentes.setFont(FuentesGUI.getFuente(FuentesGUI.Modificador.NEGRITA,
                FuentesGUI.Size.GRANDE));
    }// </editor-fold>//GEN-END:initComponents

    private void filtroEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroEmpresaActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_filtroEmpresaActionPerformed

    private void filtroEmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroEmpresaKeyPressed
        actualizarTabla();
    }//GEN-LAST:event_filtroEmpresaKeyPressed

    private void filtroEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroEmpresaKeyReleased
        actualizarTabla();
    }//GEN-LAST:event_filtroEmpresaKeyReleased

    private void filtroEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroEmpresaKeyTyped
        actualizarTabla();
    }//GEN-LAST:event_filtroEmpresaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.componentes.Etiqueta empresasDiferentes;
    private vista.componentes.Etiqueta empresasDiferentesLabel;
    private vista.componentes.Etiqueta filtroEmpesaLabel;
    private vista.componentes.TextBox filtroEmpresa;
    private javax.swing.JScrollPane jScrollPane1;
    private vista.componentes.Tabla tablaParticipaciones;
    private vista.componentes.Etiqueta titulo;
    private vista.componentes.Etiqueta totalParticipaciones;
    private vista.componentes.Etiqueta totalParticipacionesLabel;
    // End of variables declaration//GEN-END:variables

    public void actualizarDatos() {
        List<EntradaParticipacion> entradas = fa.obtenerDatosParticipaciones(u);
        listaActual = entradas;
        this.empresasDiferentes.setText(String.valueOf(entradas.size()));
        int sum = 0;
        for (EntradaParticipacion e : entradas) {
            sum += e.getNumero();
        }
        this.totalParticipaciones.setText(String.valueOf(sum));

        actualizarTabla();
        // Configurar sorts
        tablaOrdenable();

        // Sort default
        ModeloTablaParticipaciones m = (ModeloTablaParticipaciones) tablaParticipaciones.getModel();
        m.ordenarPor(3);

        this.setVisible(true);
    }

    private void tablaOrdenable() {
        JTableHeader header = tablaParticipaciones.getTableHeader();
        header.addMouseListener(new java.awt.event.MouseListener() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordenarTablaPorColumna(evt);
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }

    private void ordenarTablaPorColumna(MouseEvent evt) {
        Point point = evt.getPoint();
        int col = tablaParticipaciones.columnAtPoint(point);
        ModeloTablaParticipaciones m = (ModeloTablaParticipaciones) tablaParticipaciones.getModel();
        m.ordenarPor(col);
    }

    private void actualizarTabla() {
        ModeloTablaParticipaciones m = (ModeloTablaParticipaciones) tablaParticipaciones.getModel();
        if (listaActual == null) {
            listaActual = new ArrayList<>();
        }
        List<EntradaParticipacion> entradasFiltrar = new ArrayList<>(listaActual);
        // Filtro si no empieza con lo que hay en el textbox
        if (!this.filtroEmpresa.getText().isEmpty()) {
            entradasFiltrar.removeIf(e -> !e.getEmpresa().toLowerCase().startsWith(
                    this.filtroEmpresa.getText().toLowerCase()));
        }
        m.setFilas(entradasFiltrar);

    }
}
