package vista;

import aplicacion.EntradaHistorial;
import aplicacion.EntradaHistorial.TipoEntradaHistorial;
import aplicacion.FachadaAplicacion;
import aplicacion.Regulador;
import aplicacion.Usuario;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import vista.componentes.FuentesGUI;
import vista.componentes.ImagenesGUI;
import vista.modeloTablas.ModeloTablaHistorial;

/**
 * Ventana emergente para ver el historial y filtrarlo según diversos parámetros
 * Accesible desde VEmpresa, VInversor y VRegulador, pero con más permisos desde
 * VRegulador
 *
 * @author Pablo
 */
public class VHistorial extends javax.swing.JDialog {

    private final Usuario u;
    private boolean regulador = false;
    private final List<String> usuariosSeleccionables;
    private final List<String> tiposSeleccionables;
    private final FachadaAplicacion fa = FachadaAplicacion.getInstance();

    // Entradas en la tabla
    private List<EntradaHistorial> entradasActuales;

    // Requerido por netbeans, no usar
    public VHistorial() {
        initComponents();
        u = null;
        usuariosSeleccionables = null;
        tiposSeleccionables = null;
    }

    public VHistorial(Usuario u) {
        super();
        this.u = u;
        this.setTitle("Historial de transicciones");
        this.setIconImage(ImagenesGUI.getImage("database.png", 64));
        this.setModal(false);
        
        if (u instanceof Regulador) {
            this.regulador = true;
        }

        // Lista de usuarios seleccionables (se podrán ver sus transacciones)
        usuariosSeleccionables = new ArrayList<String>();
        if (regulador) {
            usuariosSeleccionables.add("Ver todos");
            usuariosSeleccionables.addAll(fa.obtenerListaUsuarios()
                    .stream().map(us -> us.getIdUsuario()).collect(Collectors.toList()));
        } else {
            usuariosSeleccionables.add(u.getIdUsuario());
        }

        // Lista de tipos de transaccion seleccionables
        tiposSeleccionables = new ArrayList<>();
        tiposSeleccionables.add("Ver todos");
        TipoEntradaHistorial[] tipos = EntradaHistorial.TipoEntradaHistorial.values();
        for (TipoEntradaHistorial tipo : tipos) {
            tiposSeleccionables.add(tipo.toString());
        }
        
        initComponents();
        
        this.setVisible(true);
    }

    private void actualizarTabla() {
        // Actualiza la lista del historial
        String tipoActual = (String) elegirTipo.getSelectedItem();
        Usuario usuarioActual = new Usuario((String) elegirUsuario.getSelectedItem(), false, true);

        if (regulador) {
            if (((String) elegirUsuario.getSelectedItem()).equals("Ver todos")) {
                entradasActuales = fa.obtenerHistorial();
            } else {
                entradasActuales = fa.obtenerHistorial(usuarioActual);
            }
        } else {
            entradasActuales = fa.obtenerHistorial(u);
        }

        // Filtrar
        if (tipoActual != null && (!tipoActual.equals("Ver todos"))) {
            entradasActuales.removeIf(e -> e.getTipo().toString() != tipoActual);
        }

        ModeloTablaHistorial m = (ModeloTablaHistorial) tablaHistorial.getModel();
        m.setFilas(entradasActuales);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tablaHistorial = new vista.componentes.Tabla();
        titulo = new vista.componentes.Etiqueta();
        usuarioLabel = new vista.componentes.Etiqueta();
        elegirUsuario = new vista.componentes.SelecionBox(usuariosSeleccionables.toArray());
        etiqueta1 = new vista.componentes.Etiqueta();
        elegirTipo = new vista.componentes.SelecionBox(tiposSeleccionables.toArray());
        botonVolver = new vista.componentes.Boton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaHistorial.setModel(new vista.modeloTablas.ModeloTablaHistorial()
        );
        tablaHistorial.setToolTipText("");
        jScrollPane4.setViewportView(tablaHistorial);

        titulo.setText("Historial de transacciones");

        usuarioLabel.setText("Usuario:");

        elegirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirUsuarioActionPerformed(evt);
            }
        });

        etiqueta1.setText("Tipo de transacción:");

        elegirTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirTipoActionPerformed(evt);
            }
        });

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(elegirTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(elegirUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(102, 102, 102))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(usuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(elegirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(elegirTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        titulo.setFont(FuentesGUI.getFuente(FuentesGUI.Modificador.NORMAL, FuentesGUI.Size.ENORME));
        if(!regulador)
        elegirUsuario.setEnabled(false);
        else
        elegirUsuario.setEnabled(true);

        elegirUsuario.setSelectedIndex(0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elegirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirUsuarioActionPerformed
        // TODO add your handling code here:
        actualizarTabla();
    }//GEN-LAST:event_elegirUsuarioActionPerformed

    private void elegirTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirTipoActionPerformed
        // TODO add your handling code here:
        actualizarTabla();
    }//GEN-LAST:event_elegirTipoActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.componentes.Boton botonVolver;
    private vista.componentes.SelecionBox elegirTipo;
    private vista.componentes.SelecionBox elegirUsuario;
    private vista.componentes.Etiqueta etiqueta1;
    private javax.swing.JScrollPane jScrollPane4;
    private vista.componentes.Tabla tablaHistorial;
    private vista.componentes.Etiqueta titulo;
    private vista.componentes.Etiqueta usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
