package vista;

import aplicacion.FachadaAplicacion;
import aplicacion.Empresa;
import vista.componentes.ColoresGUI;
import vista.componentes.DialogoInfo;
import vista.componentes.ImagenesGUI;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

public class VModificarEmpresa extends javax.swing.JFrame {

    private final FachadaAplicacion fa;
    private Empresa e;

    public VModificarEmpresa(Empresa e, FachadaAplicacion fa) {
        this.fa = fa;
        this.e = e;
        this.setTitle("Panel de modificación de empresa - " + e.getIdUsuario());
        this.setIconImage(ImagenesGUI.getImage("database.png", 128));

        initComponents();
        this.actualizarDatos();
        this.setValidators();
    }

    private void setValidators() {
        telefonoTextBox.setValidator(s -> {
            if (s.length() == 0) // admitimos nulos
            {
                return true;
            }
            try {
                Integer.parseInt(s);
                return s.length() == 9; // debe ser un entero de 9 cifras si no es nulo
            } catch (NumberFormatException e) {
                return false;
            }
        });
        idTextBox.setValidator(s -> s.length() > 1 && s.length() <= 20); // minimo 2, maximo 20
        nombreTextBox.setValidator(s -> s.length() > 1 && s.length() <= 60); // minimo 2, maximo 60
        direccionTextBox.setValidator(s -> s.length() <= 50); // 50 como mucho, adminitimos nulos
        cifTextBox.setValidator(s -> s.length() == 9); // debe ser 9, no admitimos nulos
        this.clave.setValidationLevel(true);
        this.claveConf.setValidationLevel(true);
        this.clave.admiteVacio(true);
        this.claveConf.admiteVacio(true);

        // Claves iguales
        claveConf.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                comprobarPassIguales();
            }

            @Override
            public void keyPressed(KeyEvent e) {
                comprobarPassIguales();
            }

            @Override
            public void keyReleased(KeyEvent e) {
                comprobarPassIguales();
            }
        });
    }

    private boolean comprobarPassIguales() {
        if (this.claveConf.getText().equals(this.clave.getText())) {
            claveConf.setBackground(ColoresGUI.blanco);
            return true;
        }
        claveConf.setBackground(ColoresGUI.getGUIColorExtraClaro(ColoresGUI.Colores.ROJO));
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idTextBox = new vista.componentes.TextBox();
        telefonoTextBox = new vista.componentes.TextBox();
        claveLabel = new vista.componentes.Etiqueta();
        nombreLabel = new vista.componentes.Etiqueta();
        clave = new vista.componentes.PasswordField();
        direccionTextBox = new vista.componentes.TextBox();
        modificarBoton = new vista.componentes.Boton();
        dniLabel = new vista.componentes.Etiqueta();
        direccionLabel = new vista.componentes.Etiqueta();
        idLabel = new vista.componentes.Etiqueta();
        claveConf = new vista.componentes.PasswordField();
        claveConfLabel = new vista.componentes.Etiqueta();
        nombreTextBox = new vista.componentes.TextBox();
        telefonoLabel = new vista.componentes.Etiqueta();
        cifTextBox = new vista.componentes.TextBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        idTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextBoxActionPerformed(evt);
            }
        });

        telefonoTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTextBoxActionPerformed(evt);
            }
        });

        claveLabel.setText("Clave:");

        nombreLabel.setText("Nombre Comercial:");

        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActionPerformed(evt);
            }
        });

        direccionTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionTextBoxActionPerformed(evt);
            }
        });

        modificarBoton.setText("Guardar modificaciones");
        modificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBotoncancelarRegistroActionPerformed(evt);
            }
        });

        dniLabel.setText("CIF:");

        direccionLabel.setText("Dirección:");

        idLabel.setText("ID de usuario:");

        claveConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveConfActionPerformed(evt);
            }
        });

        claveConfLabel.setText("Confirmación de la clave:");

        nombreTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextBoxActionPerformed(evt);
            }
        });

        telefonoLabel.setText("Teléfono:");

        cifTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifTextBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(modificarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telefonoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telefonoTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(direccionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(claveConfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(claveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(claveConf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(direccionTextBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cifTextBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(claveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(nombreTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dniLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cifTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(claveConf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(claveConfLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(telefonoTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(modificarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextBoxActionPerformed
    }//GEN-LAST:event_idTextBoxActionPerformed

    private void telefonoTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTextBoxActionPerformed
    }//GEN-LAST:event_telefonoTextBoxActionPerformed

    private void claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActionPerformed
    }//GEN-LAST:event_claveActionPerformed

    private void direccionTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTextBoxActionPerformed
    }//GEN-LAST:event_direccionTextBoxActionPerformed

    private void modificarBotoncancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBotoncancelarRegistroActionPerformed
        this.modificarEmpresa();
    }//GEN-LAST:event_modificarBotoncancelarRegistroActionPerformed

    private void claveConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveConfActionPerformed
    }//GEN-LAST:event_claveConfActionPerformed

    private void nombreTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextBoxActionPerformed
    }//GEN-LAST:event_nombreTextBoxActionPerformed

    private void cifTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifTextBoxActionPerformed
    }//GEN-LAST:event_cifTextBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.componentes.TextBox cifTextBox;
    private vista.componentes.PasswordField clave;
    private vista.componentes.PasswordField claveConf;
    private vista.componentes.Etiqueta claveConfLabel;
    private vista.componentes.Etiqueta claveLabel;
    private vista.componentes.Etiqueta direccionLabel;
    private vista.componentes.TextBox direccionTextBox;
    private vista.componentes.Etiqueta dniLabel;
    private vista.componentes.Etiqueta idLabel;
    private vista.componentes.TextBox idTextBox;
    private vista.componentes.Boton modificarBoton;
    private vista.componentes.Etiqueta nombreLabel;
    private vista.componentes.TextBox nombreTextBox;
    private vista.componentes.Etiqueta telefonoLabel;
    private vista.componentes.TextBox telefonoTextBox;
    // End of variables declaration//GEN-END:variables

    public void modificarEmpresa() {

        if (!idTextBox.validateInput() | !direccionTextBox.validateInput() | !cifTextBox.validateInput()
                | !nombreTextBox.validateInput()) {
            fa.muestraExcepcion("Alguno de los campos introducidos no es correcto!", DialogoInfo.NivelDeAdvertencia.ADVERTENCIA);
            return;
        }
        boolean passMod = false;
        if (!clave.getText().isEmpty() || !claveConf.getText().isEmpty()) {
            // Claves no vacías
            if (!clave.isValidated() | !claveConf.isValidated()) {
                String log = "";
                if (!clave.isValidated()) {
                    log = log + clave.getValidationError();
                }
                fa.muestraExcepcion(log, DialogoInfo.NivelDeAdvertencia.ADVERTENCIA);
                return;
            }
            if (!comprobarPassIguales()) {
                fa.muestraExcepcion("Las contraseñas no coinciden!", DialogoInfo.NivelDeAdvertencia.ADVERTENCIA);
                return;
            }
            passMod = true;
        }

        if (!e.getIdUsuario().equals(idTextBox.getText()) && !fa.comprobarID(this.idTextBox.getText())) {
            fa.muestraExcepcion("El nuevo ID ya está en uso!", DialogoInfo.NivelDeAdvertencia.ADVERTENCIA);
            return;
        }

        Empresa empresa = new Empresa(this.idTextBox.getText(), this.nombreTextBox.getText(), this.cifTextBox.getText(),
                0.0f, 0.0f, 0, this.direccionTextBox.getText(),
                this.telefonoTextBox.getText(), false, false);

        String pass = passMod ? this.clave.getText() : null;

        boolean insertado = fa.modificarEmpresa(empresa, pass, e.getIdUsuario());

        if (insertado) {
            this.e = fa.obtenerDatosEmpresa(empresa);
            actualizarDatos();
            fa.muestraExcepcion("Datos de la empresa modificados con éxito!", DialogoInfo.NivelDeAdvertencia.INFORMACION);
        } else {
            fa.muestraExcepcion("No se pudo modificar la base de datos.", DialogoInfo.NivelDeAdvertencia.ERROR_BASEDATOS);
        }
    }

    private void actualizarDatos() {
        this.idTextBox.setText(e.getIdUsuario());
        this.nombreTextBox.setText(e.getNombre());
        this.telefonoTextBox.setText(e.getTelefono());
        this.clave.setText("");
        this.claveConf.setText("");
        this.cifTextBox.setText(e.getCIF());
        this.direccionTextBox.setText(e.getDireccion());
    }

}
